### ISSUE TITLE
Show time zone for current lake

### ISSUE THREAD

**Issue by BjoernPetersen** [woog-life/preliminary-frontend#115]

**Comment by torbencarstens** [comment]
I though about this but wasn't entirely sure where to display this.

Any input is welcome

**Comment by torbencarstens** [comment]
maybe like this:

![image](https://github.com/woog-life/preliminary-frontend/assets/7738181/774a67b2-ee7a-42ef-b47d-38cf35b3dff1)

appending it the time makes that row somewhat too long and unwieldy

**Comment by BjoernPetersen** [comment]
I think the order of the rows is a bit confusing

**Comment by torbencarstens** [comment]
Yeah, I'm also unsure whether we can simply expose this without the extra information that this is a timezone.

I'm not sure whether the "default user" knows what a timezone normally looks like.

Maybe just as a on hover element, e.g. `timezone: America/Vancouver` (on every time element)

**Comment by torbencarstens** [comment]
maybe like this (timezone is a `title` attribute which shows on hover)

![2023-10-02T21:14:57,418185764+02:00](https://github.com/woog-life/preliminary-frontend/assets/7738181/fa8f1293-2a7a-4847-8d31-9c5f7e7b1bd8)

*I've adjusted the contrast of the link/text btw

**Comment by torbencarstens** [comment]
I've met with a focus group and got the following suggestion (`Vancouver` is from the lake name not from the timezone).

![image](https://github.com/woog-life/preliminary-frontend/assets/7738181/bca34128-43ab-46ee-8238-d640ddad6714)

> I'm not sure whether the "default user" knows what a timezone normally looks like.

Unsurprisingly, no

**Comment by torbencarstens** [comment]
I've pushed this ^ as a test (ef7a3191ce3e71ece64bb3cc955661cb6a3b63cc), we can change this later on if we decide on something nicer.

btw, this https://github.com/woog-life/api/issues/18 was an input as well. Not only for local wather data but also for a link to a map (OSM/google).
