### ISSUE TITLE
Use mutli-stage Dockerfile for building

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/preliminary-frontend#35]

**Comment by RishiKumarRay** [comment]
Can you elaborate what we have too?

**Comment by torbencarstens** [comment]
@RishiKumarRay currently the building step (https://github.com/woog-life/preliminary-frontend/blob/master/.github/workflows/build_publish.yml#L24) is done on the github actions runner, the `public` folder is then added into the Dockerfile (https://github.com/woog-life/preliminary-frontend/blob/master/Dockerfile#L4).

This is suboptimal since you need to have all the necessary dev tools installed for building/running this project locally.

The first stage of the Dockerfile should build the project, the second stage should copy the public folder from the first stage. We want to do this in two stages to reduce the size and complexity of the final docker image while also increasing security (less components -> less attack vectors).

**Comment by RishiKumarRay** [comment]
@torbencarstens Can you tell me how this project is build locally, that will help me in writing this docker file .
And please assign this to me

**Comment by torbencarstens** [comment]
Since this successfully build via the pipeline you just have to follow the steps in the pipeline build step (https://github.com/woog-life/preliminary-frontend/blob/master/.github/workflows/build.yml#L21)

1. Have dotnet-sdk 3.1.x installed (you could use `mcr.microsoft.com/dotnet/sdk:3.1` as a base image for the first stage)
2. Have nodejs/npm installed (use nodejs version `17.x`)
3. Replace some placeholders (sed calls) -> `OPENWEATHERMAP_APIKEY_RAW` and `GITHUB_SHA` need to be passed into the docker build as environment variables and used there
4. Install dependencies via `npm install`
5. Build production app via `npm prod`
6. Copy the public folder into the second stage (to /usr/share/nginx/html`)

**Comment by DipayanP007** [comment]
Hey @torbencarstens I have worked on this issue and created a PR

**Comment by RishiKumarRay** [comment]
@torbencarstens yeah please review his PR, he is my friend , i was busy so i had given him this issue, he wanted to make a contribution, thanks
